version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: authdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    environment:
      DATABASE_URL: postgres://admin:admin@postgres:5432/authdb
    depends_on:
      postgres:
        condition: service_started
    ports:
      - "4000:4000"
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm start"

  frontend:
    build:
      context: ./frontend
    depends_on:
      backend:
        condition: service_started
    ports:
      - "3000:3000"

volumes:
  postgres_data:
